INSERT into Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom)
VALUES ('client@example.com', 'smdfgsdfg', "client", '2000-01-01', 'Michelle', 'trou');

INSERT into Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom)
VALUES ('admin@example.com', 'dddz', "admin", '2000-01-01', 'Bernard', 'Malin');




  INSERT INTO Produit (Nom, Description, Prix, Promotion, Sexe, nb_image, Mail) VALUES
  ('T-shirt blanc personnalisé', "Ce t-shirt blanc classique est un incontournable de la garde-robe. Avec sa coupe ajustée et son tissu doux, il est parfait pour un look décontracté. Portez-le avec un jean pour un style casual ou sous une veste pour un look plus habillé.", 15.99, 'Non', 'Unisexe', '1', 'admin@example.com'),
  ('Pull marron', "Ce pull marron court est à la fois chic et confortable. Fabriqué dans un tricot doux, il présente une coupe courte et ajustée, parfaite pour une silhouette moderne. Sa couleur marron terre lui donne un aspect chaleureux et polyvalent. Idéal pour superposer sur une chemise ou porter avec un jean pour un look décontracté mais élégant.", 29.99, 'Oui', 'Unisexe', '8', 'admin@example.com'),
  ('Pull pour enfant', "Ce petit pull pour enfant est adorable et fonctionnel. Fabriqué dans un tricot doux, il présente une coupe ajustée qui assure confort et chaleur. Avec son design simple et ses couleurs vives, il est parfait pour toutes les occasions, que ce soit pour jouer à l'extérieur ou pour une journée à l'école. Un incontournable de la garde-robe hivernale des plus jeunes !", 49.99, 'Non', 'Enfant', '2', 'admin@example.com'),
  ('Veste Noir', "Cette veste noire incarne l'élégance intemporelle. Avec son design sobre et épuré, elle s'adapte à toutes les tenues, des plus décontractées aux plus habillées. Fabriquée dans un tissu de qualité, elle offre à la fois confort et style. Parfaite pour affronter le froid avec classe ou pour compléter un look sophistiqué en toute simplicité.", 59.99, 'Non', 'Homme', '4', 'admin@example.com'),
  ('Sweat rose'," Ce sweat rose est à la fois doux et tendance. Fabriqué dans un tissu confortable, il offre une sensation agréable contre la peau. Sa couleur rose douce ajoute une touche de féminité et de fraîcheur à n'importe quelle tenue. Avec sa coupe décontractée et ses finitions soignées, il est parfait pour les journées décontractées ou les séances d'entraînement. Un essentiel de la garde-robe pour ajouter une touche de couleur et de style à votre look quotidien.", 39.99, 'Oui', 'Femme', '6', 'admin@example.com'),
  ('Sweat violet'," Ce sweat violet est à la fois élégant et confortable. Fabriqué dans un tissu doux, il offre une sensation agréable contre la peau. Sa couleur violette vibrante ajoute une touche d'originalité et de sophistication à votre tenue. Avec sa coupe moderne et ses détails soignés, il est parfait pour les journées décontractées ou les moments de détente à la maison. Un choix parfait pour ceux qui recherchent à la fois style et confort dans leur garde-robe.", 24.99, 'Non', 'Unisexe', '4', 'admin@example.com'),
  ('Sweat noir', "Ce sweat noir incarne l'élégance intemporelle. Fabriqué dans un tissu doux et confortable, il offre une sensation agréable contre la peau. Sa couleur noire classique lui confère une polyvalence qui s'adapte à toutes les tenues et occasions. Avec sa coupe décontractée et ses finitions soignées, c'est un choix parfait pour les journées décontractées ou les séances d'entraînement. Un essentiel de la garde-robe qui allie style et confort avec facilité.", 34.99, 'Non', 'Unisexe', '4', 'admin@example.com'),
  ('Robe blanche'," Cette robe blanche est synonyme de pureté et d'élégance. Fabriquée dans un tissu léger et fluide, elle offre un confort optimal tout en mettant en valeur la silhouette. Son design épuré et intemporel en fait un choix parfait pour une multitude d'occasions, que ce soit pour une soirée chic, un cocktail en plein air ou une journée en ville. La couleur blanche apporte une touche de fraîcheur et de sophistication, tandis que sa coupe flatteuse souligne subtilement les courbes féminines. Une pièce incontournable pour toute garde-robe, offrant une toile parfaite pour exprimer votre style personnel.", 79.99, 'Non', 'Femme', '3', 'admin@example.com'),
  ('Robe blanche'," Cette robe blanche est synonyme de pureté et d'élégance. Fabriquée dans un tissu léger et fluide, elle offre un confort optimal tout en mettant en valeur la silhouette. Son design épuré et intemporel en fait un choix parfait pour une multitude d'occasions, que ce soit pour une soirée chic, un cocktail en plein air ou une journée en ville. La couleur blanche apporte une touche de fraîcheur et de sophistication, tandis que sa coupe flatteuse souligne subtilement les courbes féminines. Une pièce incontournable pour toute garde-robe, offrant une toile parfaite pour exprimer votre style personnel.", 79.99, 'Non', 'Femme', '3', 'admin@example.com'),
  ('Robe bleue', "Cette robe bleue incarne l'élégance et la sophistication. Fabriquée dans un tissu de qualité, elle offre un tombé fluide et confortable. Sa couleur bleue vibrante ajoute une touche de fraîcheur et de modernité à votre tenue. Avec sa coupe classique et ses détails raffinés, elle est parfaite pour toutes les occasions, qu'il s'agisse d'un cocktail, d'une soirée formelle ou d'une journée spéciale. La robe bleue est un choix polyvalent qui mettra en valeur votre style avec élégance et assurance.", 89.99, 'Oui', 'Femme', '4', 'admin@example.com'),
  ('Robe enfant'," Cette robe blanche pour enfant est à la fois adorable et élégante. Fabriquée dans un tissu léger et doux, elle offre un confort optimal pour les petites princesses. Son design simple et épuré est parfait pour toutes les occasions spéciales, que ce soit pour un mariage, une fête d'anniversaire ou une journée à la plage. La couleur blanche apporte une touche de pureté et d'innocence, tandis que les petits détails comme les volants ou les broderies ajoutent une touche de charme supplémentaire. Une pièce essentielle pour toute jeune fille qui veut se sentir belle et spéciale lors des moments importants de sa vie.", 19.99, 'Non', 'Enfant', '4', 'admin@example.com'),
  ('Veste marron pour femme',"Cette veste marron est à la fois polyvalente et stylée. Fabriquée dans un tissu de qualité, elle offre à la fois chaleur et confort. Sa couleur marron terre lui confère un aspect intemporel et élégant, facile à assortir avec différentes tenues. Avec sa coupe classique et ses finitions soignées, elle est parfaite pour les journées fraîches d'automne ou les soirées décontractées. Que ce soit pour une promenade en ville ou une sortie entre amis, cette veste marron vous gardera à la fois au chaud et à la mode.", 79.99, 'Non', 'Femme', '3', 'admin@example.com'),
  ('Robe blanche', "Cette robe blanche est une véritable ode à l'élégance et à la fraîcheur. Fabriquée dans un tissu léger et délicat, elle épouse gracieusement les courbes féminines tout en offrant un confort optimal. Son allure épurée et immaculée en fait une pièce parfaite pour une variété d'occasions, que ce soit pour une cérémonie de mariage, une soirée estivale ou une promenade romantique sur la plage. La couleur blanche symbolise la pureté et l'innocence, tandis que les détails subtils, comme les dentelles ou les broderies, ajoutent une touche de sophistication et de charme. Cette robe blanche est un choix intemporel qui vous fera briller avec grâce et élégance où que vous alliez.", 59.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('Pull bleue'," Ce pull bleu pour femme est à la fois chic et confortable. Fabriqué dans un tricot doux et extensible, il offre une sensation agréable contre la peau tout en épousant élégamment les courbes féminines. Sa couleur bleue vibrante apporte une touche de fraîcheur et de modernité à votre tenue. Avec sa coupe ajustée et ses finitions soignées, il est parfait pour les journées fraîches d'automne ou les soirées décontractées. Associez-le à un jean pour un look casual élégant, ou à une jupe pour une allure plus sophistiquée. Ce pull bleu est un indispensable de la garde-robe féminine, offrant style et confort en toute saison.", 49.99, 'Non', 'Femme', '2', 'admin@example.com'),
  ('Jean pour femme '," Ce jean pour femme est un classique intemporel. Fabriqué dans un denim de qualité, il offre à la fois style et confort. Sa coupe ajustée met en valeur la silhouette féminine tout en assurant une grande liberté de mouvement. La couleur bleue indigo apporte une touche de polyvalence et s'harmonise facilement avec une variété de hauts et de chaussures. Doté de détails subtils comme des surpiqûres contrastantes ou des boutons décoratifs, ce jean ajoute une touche d'élégance à toute tenue décontractée. Parfait pour une journée de détente en ville ou une soirée entre amis, ce jean pour femme est un essentiel de la garde-robe qui vous accompagnera avec style au quotidien.", 39.99, 'Non', 'Femme', '4', 'admin@example.com'),
  ('Survêtement Beige'," Ce survêtement est à la fois confortable et stylé. Fabriqué dans un tissu doux et extensible, il offre une liberté de mouvement optimale lors de vos séances d'entraînement ou de vos activités quotidiennes. Le haut est doté d'une fermeture éclair pour un enfilage facile, tandis que le pantalon présente une taille élastique et des poches pratiques. Avec son design épuré et ses lignes dynamiques, ce survêtement est parfait pour les sportifs soucieux de leur style. Disponible dans une variété de couleurs tendance, il vous permettra de rester confortablement chic, que ce soit sur le terrain ou dans la rue.", 129.99, 'Non', 'Homme', '4', 'admin@example.com'),
  ("Robe d'été", "Cette robe d'été est une invitation à la légèreté et à la fraîcheur. Fabriquée dans un tissu léger et aéré, elle offre un confort optimal même par les journées les plus chaudes. Son design estival se caractérise par des motifs floraux ou des rayures colorées, ajoutant une touche de gaieté à votre look. La coupe fluide et la taille ajustable assurent une silhouette flatteuse pour toutes les morphologies. Avec ses bretelles fines ou son décolleté délicat, cette robe est parfaite pour flâner en bord de mer, se promener en ville ou profiter d'un barbecue entre amis. Une pièce incontournable de votre garde-robe estivale, pour un style décontracté et élégant à la fois.",29.99,"Non","Femme", '4', 'admin@example.com'),
  ('Veste Rembourée pour enfant rose'," Cette veste rembourrée rose pour enfant est à la fois adorable et fonctionnelle. Fabriquée dans un tissu résistant et doux, elle offre une chaleur optimale tout en étant confortable à porter. Sa couleur rose vif apporte une touche de gaieté à la tenue de votre enfant. Dotée d'une capuche pour protéger des intempéries et de poches pratiques pour garder les petites mains au chaud, elle est parfaite pour les journées fraîches d'automne ou d'hiver. Avec son design léger et ses finitions soignées, cette veste rembourrée est un choix idéal pour que votre enfant reste au chaud et stylé lors de ses activités en extérieur.", 49.99, 'Oui', 'Enfant', '2', 'admin@example.com'),
  ('Combinaison bleue en jean pour fille', "Cette combinaison bleue en jean pour fille est à la fois confortable et tendance. Fabriquée dans un denim de qualité, elle offre un style décontracté parfait pour les journées d'aventure. Sa coupe ajustée et ses détails élégants en font une tenue polyvalente pour toutes les occasions. Que ce soit pour jouer à l'extérieur ou pour une journée à l'école, cette combinaison sera le choix idéal pour votre petite fashionista.", 39.99, 'Non', 'Enfant', '1', 'admin@example.com'),
  ('Marinière pour enfant', "Cette marinière pour enfant est un classique intemporel. Fabriquée dans un tissu de qualité, elle offre à la fois confort et style. Ses rayures marines apportent une touche de fraîcheur à n'importe quelle tenue. Parfaite pour une journée à la plage ou une sortie en famille, cette marinière sera le choix parfait pour votre enfant.", 29.99, 'Non', 'Enfant', 'nb_img=1', 'admin@example.com'),
  ('Robe de mariée blanche pour femme', "Cette robe de mariée blanche pour femme est un rêve devenu réalité. Fabriquée dans un tissu de qualité supérieure, elle offre une silhouette élégante et féminine. Sa coupe ajustée met en valeur les courbes de votre corps, tandis que ses détails délicats ajoutent une touche de glamour à votre look. Que vous vous promeniez dans l'allée ou que vous dansiez toute la nuit, cette robe de mariée vous fera vous sentir comme une princesse.", 499.99, 'Non', 'Femme', '1', 'admin@example.com'),
  ('Robe rouge salsa pour femme', "Cette robe rouge salsa pour femme est parfaite pour faire tourner les têtes. Fabriquée dans un tissu extensible de haute qualité, elle épouse vos courbes de manière flatteuse. Sa couleur vive et ses volants élégants ajoutent une touche de sensualité à votre look. Que ce soit pour une soirée dansante ou une occasion spéciale, cette robe sera sûre de faire sensation.", 59.99, 'Non', 'Femme', '1', 'admin@example.com'),
  ('Robe noire gothique pour femme', "Cette robe noire gothique pour femme est un véritable chef-d'œuvre de l'obscurité. Fabriquée dans un tissu de qualité supérieure, elle présente des détails complexes et des finitions soignées. Sa coupe élégante et ses accents gothiques en font une tenue parfaite pour les amateurs de mode sombre. Que ce soit pour une soirée en ville ou une convention de cosplay, cette robe sera sûre de vous démarquer de la foule.", 79.99, 'Non', 'Femme', '1', 'admin@example.com'),
  ('Pull en laine blanche pour femme', "Ce pull en laine blanche pour femme est à la fois confortable et élégant. Fabriqué dans une laine de qualité, il offre une chaleur optimale tout en étant léger et doux au toucher. Sa coupe décontractée et ses finitions soignées en font un incontournable de votre garde-robe d'hiver. Que ce soit pour une journée de détente à la maison ou une sortie entre amis, ce pull sera votre allié contre le froid.", 89.99, 'Non', 'Femme', '1', 'admin@example.com'),
  ('Chemisette kimono liberty rouge fleurie pour enfant', "Cette chemisette kimono liberty rouge fleurie pour enfant est à la fois confortable et stylée. Fabriquée dans un tissu léger et respirant, elle offre une liberté de mouvement optimale pour votre petit aventurier. Son motif floral et ses détails élégants ajoutent une touche de fraîcheur à n'importe quelle tenue. Parfaite pour une journée à l'école ou une sortie en famille, cette chemisette sera le choix idéal pour votre enfant.", 34.99, 'Non', 'Enfant', '1', 'admin@example.com'),
  ('Sweat gris', "Ce sweat-shirt gris associe confort et style avec sa coupe classique, son tissu doux et sa couleur polyvalente. Doté d'une poche kangourou à l'avant, c'est un choix parfait pour rester tendance lors des journées fraîches.", 15.99, 'Non', 'Unisexe', '4', 'admin@example.com'),
  ('T-shirt blanc', "Ce t-shirt blanc classique est un incontournable de la garde-robe. Avec sa coupe ajustée et son tissu doux, il est parfait pour un look décontracté. Portez-le avec un jean pour un style casual ou sous une veste pour un look plus habillé.", 15.99, 'Non', 'homme', '1', 'admin@example.com'),
  ('Veste matelassée rose pour femme', "Cette veste matelassée rose pour femme est à la fois chic et confortable. Son design matelassé lui confère une allure élégante, tandis que sa couleur rose tendre apporte une touche de douceur à votre tenue. Fabriquée dans un tissu de haute qualité, elle vous garde au chaud tout en vous assurant un grand confort. Avec sa coupe ajustée et ses finitions soignées, cette veste est parfaite pour affronter les journées fraîches avec style.", 69.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('Chemise en lin avec dentelle pour petite fille enfant', "Cette charmante chemise en laine avec dentelle est parfaite pour habiller votre petite fille avec élégance et confort. Fabriquée dans un mélange de laine douce, elle offre une chaleur optimale tout en étant agréable à porter. La dentelle délicate ajoutée sur le col et les poignets apporte une touche de féminité à cette pièce intemporelle. Avec sa coupe classique et ses finitions raffinées, cette chemise est idéale pour les occasions spéciales ou simplement pour ajouter une touche d'élégance au quotidien de votre enfant.", 39.99, 'Oui', 'Enfant', '1', 'admin@example.com'),
  ('T-shirt blanc pour enfant', "Ce t-shirt blanc pour enfant est un essentiel de toute garde-robe. Fabriqué dans un coton doux et respirant, il offre un confort optimal tout au long de la journée. Sa couleur blanche polyvalente se marie facilement avec une variété de tenues, en faisant un choix parfait pour toutes les occasions. Avec sa coupe classique et ses finitions de qualité, ce t-shirt est un basique intemporel que votre enfant adorera porter encore et encore.", 19.99, 'Oui', 'Enfant', '1', 'admin@example.com'),
  ('Combinaison blanche pour femme', "Cette combinaison blanche pour femme est à la fois élégante et confortable. Fabriquée dans un tissu léger et fluide, elle offre une grande liberté de mouvement tout en mettant en valeur votre silhouette. Son design épuré et sa couleur blanche intemporelle en font une pièce polyvalente, parfaite pour toutes les occasions. Que ce soit pour une soirée chic ou une journée décontractée, cette combinaison est un choix sûr pour un look tendance et sophistiqué.", 79.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('Escarpin blanc pour femme', "Ces escarpins blancs pour femme sont le parfait mélange entre élégance et confort. Leur design classique et épuré en fait des chaussures polyvalentes, parfaites pour compléter n'importe quelle tenue, qu'elle soit décontractée ou habillée. Fabriqués dans un cuir de qualité, ils offrent un confort optimal tout au long de la journée. Leur couleur blanche intemporelle en fait des indispensables de toute garde-robe féminine.", 89.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('Robe blanche pour femme', "Cette ravissante robe blanche pour femme est un véritable classique intemporel. Son design élégant et féminin en fait une pièce polyvalente, parfaite pour toutes les occasions, des soirées spéciales aux journées décontractées. Fabriquée dans un tissu léger et fluide, elle offre un confort optimal tout en mettant en valeur votre silhouette. Que ce soit avec des talons hauts pour une allure sophistiquée ou des sandales plates pour un look plus décontracté, cette robe est un choix sûr pour un style chic et élégant.", 99.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('Robe blanche style nuisette pour femme', "Cette robe blanche au style nuisette pour femme est à la fois sexy et élégante. Son design épuré et fluide met en valeur votre silhouette, tandis que sa couleur blanche intemporelle lui confère une touche de sophistication. Parfaite pour une soirée spéciale ou une occasion formelle, cette robe est un choix sûr pour un look à la fois tendance et glamour.", 129.99, 'Oui', 'Femme', '2', 'admin@example.com'),
  ('Robe violette sexy pour femme', "Cette robe violette sexy pour femme est parfaite pour faire tourner les têtes lors de vos soirées spéciales. Son design audacieux et sensuel met en valeur votre silhouette, tandis que sa couleur violette vibrante lui confère une touche de glamour. Fabriquée dans un tissu stretch confortable, elle épouse vos courbes pour un look à la fois sexy et élégant. Que ce soit pour une soirée en amoureux ou une sortie entre amies, cette robe est un choix sûr pour un style irrésistible.", 149.99, 'Oui', 'Femme', '1', 'admin@example.com'),
  ('T-shirt sexy pour femme', "Ce t-shirt sexy pour femme est le parfait mélange entre confort et style. Fabriqué dans un tissu doux et extensible, il offre une coupe ajustée qui met en valeur votre silhouette. Son design audacieux et sensuel est parfait pour ajouter une touche de glamour à votre tenue, que ce soit avec un jean décontracté ou une jupe élégante. Disponible dans une variété de couleurs tendance, ce t-shirt est un choix sûr pour un look sexy et sophistiqué.", 49.99, 'Oui', 'Femme', '1', 'admin@example.com');
  
  

INSERT INTO Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom) 
VALUES
    ('baptiste.chesnot@gmail.com', '1234', 'client', '1990-01-01', 'Chesnot', 'Baptiste'),
    ('utilisateur2@example.com', 'hash2', 'client', '1991-02-02', 'Smith', 'Alice'),
    ('utilisateur3@example.com', 'hash3', 'client', '1992-03-03', 'Johnson', 'Bob'),
    ('utilisateur4@example.com', 'hash4', 'client', '1993-04-04', 'Brown', 'Emily'),
    ('utilisateur5@example.com', 'hash5', 'client', '1994-05-05', 'Wilson', 'Mike'),
    ('utilisateur6@example.com', 'hash6', 'client', '1995-06-06', 'Taylor', 'Sarah'),
    ('utilisateur7@example.com', 'hash7', 'client', '1996-07-07', 'Anderson', 'Laura'),
    ('utilisateur8@example.com', 'hash8', 'client', '1997-08-08', 'Thomas', 'David'),
    ('utilisateur9@example.com', 'hash9', 'client', '1998-09-09', 'Jackson', 'Jessica'),
    ('utilisateur10@example.com', 'hash10', 'client', '1999-10-10', 'White', 'Chris');

INSERT INTO Produit (Nom, Description, Prix, Promotion, Sexe, nb_image, Mail) VALUES
                                                                                  ('T-shirt blanc', 'Un t-shirt blanc classique', 15.99, 'Non', 'Unisexe', '', 'baptiste.chesnot@gmail.com'),
                                                                                  ('Jeans noir', 'Un jean noir tendance', 29.99, 'Oui', 'Homme', '', 'baptiste.chesnot@gmail.com');