INSERT into Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom)
VALUES ('client@example.com', 'smdfgsdfg', "client", '2000-01-01', 'Michelle', 'trou');

INSERT into Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom)
VALUES ('admin@example.com', 'dddz', "admin", '2000-01-01', 'Bernard', 'Malin');




  INSERT INTO Produit (Nom, Description, Prix, Promotion, Sexe, nb_image, Mail) VALUES
  ('Sweat gris', "Ce sweat-shirt gris associe confort et style avec sa coupe classique, son tissu doux et sa couleur polyvalente. Doté d'une poche kangourou à l'avant, c'est un choix parfait pour rester tendance lors des journées fraîches.", 15.99, 'Non', 'Unisexe', '', 'admin@example.com'),
  ('Pull marron', "Ce pull marron court est à la fois chic et confortable. Fabriqué dans un tricot doux, il présente une coupe courte et ajustée, parfaite pour une silhouette moderne. Sa couleur marron terre lui donne un aspect chaleureux et polyvalent. Idéal pour superposer sur une chemise ou porter avec un jean pour un look décontracté mais élégant.", 29.99, 'Oui', 'Unisexe', '', 'admin@example.com'),
  ('Pull pour enfant', "Ce petit pull pour enfant est adorable et fonctionnel. Fabriqué dans un tricot doux, il présente une coupe ajustée qui assure confort et chaleur. Avec son design simple et ses couleurs vives, il est parfait pour toutes les occasions, que ce soit pour jouer à l'extérieur ou pour une journée à l'école. Un incontournable de la garde-robe hivernale des plus jeunes !", 49.99, 'Non', 'Enfant', '', 'admin@example.com'),
  ('Veste Noir', "Cette veste noire incarne l'élégance intemporelle. Avec son design sobre et épuré, elle s'adapte à toutes les tenues, des plus décontractées aux plus habillées. Fabriquée dans un tissu de qualité, elle offre à la fois confort et style. Parfaite pour affronter le froid avec classe ou pour compléter un look sophistiqué en toute simplicité.", 59.99, 'Non', 'Homme', '', 'admin@example.com'),
  ('Sweat rose'," Ce sweat rose est à la fois doux et tendance. Fabriqué dans un tissu confortable, il offre une sensation agréable contre la peau. Sa couleur rose douce ajoute une touche de féminité et de fraîcheur à n'importe quelle tenue. Avec sa coupe décontractée et ses finitions soignées, il est parfait pour les journées décontractées ou les séances d'entraînement. Un essentiel de la garde-robe pour ajouter une touche de couleur et de style à votre look quotidien.", 39.99, 'Oui', 'Femme', '', 'admin@example.com'),
  ('Sweat violet'," Ce sweat violet est à la fois élégant et confortable. Fabriqué dans un tissu doux, il offre une sensation agréable contre la peau. Sa couleur violette vibrante ajoute une touche d'originalité et de sophistication à votre tenue. Avec sa coupe moderne et ses détails soignés, il est parfait pour les journées décontractées ou les moments de détente à la maison. Un choix parfait pour ceux qui recherchent à la fois style et confort dans leur garde-robe.", 24.99, 'Non', 'Unisexe', '', 'admin@example.com'),
  ('Sweat noir', "Ce sweat noir incarne l'élégance intemporelle. Fabriqué dans un tissu doux et confortable, il offre une sensation agréable contre la peau. Sa couleur noire classique lui confère une polyvalence qui s'adapte à toutes les tenues et occasions. Avec sa coupe décontractée et ses finitions soignées, c'est un choix parfait pour les journées décontractées ou les séances d'entraînement. Un essentiel de la garde-robe qui allie style et confort avec facilité.", 34.99, 'Non', 'Unisexe', '', 'admin@example.com'),
  ('Robe blanche'," Cette robe blanche est synonyme de pureté et d'élégance. Fabriquée dans un tissu léger et fluide, elle offre un confort optimal tout en mettant en valeur la silhouette. Son design épuré et intemporel en fait un choix parfait pour une multitude d'occasions, que ce soit pour une soirée chic, un cocktail en plein air ou une journée en ville. La couleur blanche apporte une touche de fraîcheur et de sophistication, tandis que sa coupe flatteuse souligne subtilement les courbes féminines. Une pièce incontournable pour toute garde-robe, offrant une toile parfaite pour exprimer votre style personnel.", 79.99, 'Non', 'Femme', '', 'admin@example.com'),
  ('Robe bleue', "Cette robe bleue incarne l'élégance et la sophistication. Fabriquée dans un tissu de qualité, elle offre un tombé fluide et confortable. Sa couleur bleue vibrante ajoute une touche de fraîcheur et de modernité à votre tenue. Avec sa coupe classique et ses détails raffinés, elle est parfaite pour toutes les occasions, qu'il s'agisse d'un cocktail, d'une soirée formelle ou d'une journée spéciale. La robe bleue est un choix polyvalent qui mettra en valeur votre style avec élégance et assurance.", 89.99, 'Oui', 'Femme', '', 'admin@example.com'),
  ('Robe enfant'," Cette robe blanche pour enfant est à la fois adorable et élégante. Fabriquée dans un tissu léger et doux, elle offre un confort optimal pour les petites princesses. Son design simple et épuré est parfait pour toutes les occasions spéciales, que ce soit pour un mariage, une fête d'anniversaire ou une journée à la plage. La couleur blanche apporte une touche de pureté et d'innocence, tandis que les petits détails comme les volants ou les broderies ajoutent une touche de charme supplémentaire. Une pièce essentielle pour toute jeune fille qui veut se sentir belle et spéciale lors des moments importants de sa vie.", 19.99, 'Non', 'Enfant', '', 'admin@example.com'),
  ('Veste marron pour femme',"Cette veste marron est à la fois polyvalente et stylée. Fabriquée dans un tissu de qualité, elle offre à la fois chaleur et confort. Sa couleur marron terre lui confère un aspect intemporel et élégant, facile à assortir avec différentes tenues. Avec sa coupe classique et ses finitions soignées, elle est parfaite pour les journées fraîches d'automne ou les soirées décontractées. Que ce soit pour une promenade en ville ou une sortie entre amis, cette veste marron vous gardera à la fois au chaud et à la mode.", 79.99, 'Non', 'Femme', '', 'admin@example.com'),
  ('Baskets blanches', 'Des baskets blanches classiques', 49.99, 'Non', 'Unisexe', '', 'admin@example.com'),
  ('Robe blanche', "Cette robe blanche est une véritable ode à l'élégance et à la fraîcheur. Fabriquée dans un tissu léger et délicat, elle épouse gracieusement les courbes féminines tout en offrant un confort optimal. Son allure épurée et immaculée en fait une pièce parfaite pour une variété d'occasions, que ce soit pour une cérémonie de mariage, une soirée estivale ou une promenade romantique sur la plage. La couleur blanche symbolise la pureté et l'innocence, tandis que les détails subtils, comme les dentelles ou les broderies, ajoutent une touche de sophistication et de charme. Cette robe blanche est un choix intemporel qui vous fera briller avec grâce et élégance où que vous alliez.", 59.99, 'Oui', 'Femme', '', 'admin@example.com'),
  ('Pull bleue'," Ce pull bleu pour femme est à la fois chic et confortable. Fabriqué dans un tricot doux et extensible, il offre une sensation agréable contre la peau tout en épousant élégamment les courbes féminines. Sa couleur bleue vibrante apporte une touche de fraîcheur et de modernité à votre tenue. Avec sa coupe ajustée et ses finitions soignées, il est parfait pour les journées fraîches d'automne ou les soirées décontractées. Associez-le à un jean pour un look casual élégant, ou à une jupe pour une allure plus sophistiquée. Ce pull bleu est un indispensable de la garde-robe féminine, offrant style et confort en toute saison.", 49.99, 'Non', 'Femme', '', 'admin@example.com'),
  ('Jean pour femme '," Ce jean pour femme est un classique intemporel. Fabriqué dans un denim de qualité, il offre à la fois style et confort. Sa coupe ajustée met en valeur la silhouette féminine tout en assurant une grande liberté de mouvement. La couleur bleue indigo apporte une touche de polyvalence et s'harmonise facilement avec une variété de hauts et de chaussures. Doté de détails subtils comme des surpiqûres contrastantes ou des boutons décoratifs, ce jean ajoute une touche d'élégance à toute tenue décontractée. Parfait pour une journée de détente en ville ou une soirée entre amis, ce jean pour femme est un essentiel de la garde-robe qui vous accompagnera avec style au quotidien.", 39.99, 'Non', 'Femme', '', 'admin@example.com'),
  ('Survêtement Beige'," Ce survêtement est à la fois confortable et stylé. Fabriqué dans un tissu doux et extensible, il offre une liberté de mouvement optimale lors de vos séances d'entraînement ou de vos activités quotidiennes. Le haut est doté d'une fermeture éclair pour un enfilage facile, tandis que le pantalon présente une taille élastique et des poches pratiques. Avec son design épuré et ses lignes dynamiques, ce survêtement est parfait pour les sportifs soucieux de leur style. Disponible dans une variété de couleurs tendance, il vous permettra de rester confortablement chic, que ce soit sur le terrain ou dans la rue.", 129.99, 'Non', 'Homme', '', 'admin@example.com'),
  ("Robe d'été", "Cette robe d'été est une invitation à la légèreté et à la fraîcheur. Fabriquée dans un tissu léger et aéré, elle offre un confort optimal même par les journées les plus chaudes. Son design estival se caractérise par des motifs floraux ou des rayures colorées, ajoutant une touche de gaieté à votre look. La coupe fluide et la taille ajustable assurent une silhouette flatteuse pour toutes les morphologies. Avec ses bretelles fines ou son décolleté délicat, cette robe est parfaite pour flâner en bord de mer, se promener en ville ou profiter d'un barbecue entre amis. Une pièce incontournable de votre garde-robe estivale, pour un style décontracté et élégant à la fois.",29.99,"Non","Femme", '', 'admin@example.com'),
  ('Veste Rembourée pour enfant rose'," Cette veste rembourrée rose pour enfant est à la fois adorable et fonctionnelle. Fabriquée dans un tissu résistant et doux, elle offre une chaleur optimale tout en étant confortable à porter. Sa couleur rose vif apporte une touche de gaieté à la tenue de votre enfant. Dotée d'une capuche pour protéger des intempéries et de poches pratiques pour garder les petites mains au chaud, elle est parfaite pour les journées fraîches d'automne ou d'hiver. Avec son design léger et ses finitions soignées, cette veste rembourrée est un choix idéal pour que votre enfant reste au chaud et stylé lors de ses activités en extérieur.", 49.99, 'Oui', 'Enfant', '', 'admin@example.com');
  
  

INSERT INTO Utilisateur (Mail, Hash_mdp, Type_utilisateur, Date_de_naissance, Nom, Prenom) 
VALUES
    ('baptiste.chesnot@gmail.com', '1234', 'client', '1990-01-01', 'Chesnot', 'Baptiste'),
    ('utilisateur2@example.com', 'hash2', 'client', '1991-02-02', 'Smith', 'Alice'),
    ('utilisateur3@example.com', 'hash3', 'client', '1992-03-03', 'Johnson', 'Bob'),
    ('utilisateur4@example.com', 'hash4', 'client', '1993-04-04', 'Brown', 'Emily'),
    ('utilisateur5@example.com', 'hash5', 'client', '1994-05-05', 'Wilson', 'Mike'),
    ('utilisateur6@example.com', 'hash6', 'client', '1995-06-06', 'Taylor', 'Sarah'),
    ('utilisateur7@example.com', 'hash7', 'client', '1996-07-07', 'Anderson', 'Laura'),
    ('utilisateur8@example.com', 'hash8', 'client', '1997-08-08', 'Thomas', 'David'),
    ('utilisateur9@example.com', 'hash9', 'client', '1998-09-09', 'Jackson', 'Jessica'),
    ('utilisateur10@example.com', 'hash10', 'client', '1999-10-10', 'White', 'Chris');

INSERT INTO Produit (Nom, Description, Prix, Promotion, Sexe, nb_image, Mail) VALUES
                                                                                  ('T-shirt blanc', 'Un t-shirt blanc classique', 15.99, 'Non', 'Unisexe', '', 'baptiste.chesnot@gmail.com'),
                                                                                  ('Jeans noir', 'Un jean noir tendance', 29.99, 'Oui', 'Homme', '', 'baptiste.chesnot@gmail.com');